name: korova
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - backcall=0.1.0
  - blas=1.0
  - bokeh=1.4.0
  - ca-certificates=2020.1.1
  - certifi=2019.11.28
  - click=7.0
  - cytoolz=0.10.1
  - dask=2.10.1
  - dask-core=2.10.1
  - decorator=4.4.1
  - distributed=2.10.0
  - freetype=2.9.1
  - fsspec=0.6.2
  - heapdict=1.0.1
  - intel-openmp=2020.0
  - ipython=7.12.0
  - ipython_genutils=0.2.0
  - jedi=0.16.0
  - jinja2=2.11.1
  - jpeg=9b
  - ld_impl_linux-64=2.33.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcxx=9.0.1
  - libcxxabi=9.0.1
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgcc-ng=9.2.0
  - libgfortran=3.0.0
  - libgfortran-ng=7.3.0
  - libgomp=9.2.0
  - liblapack=3.8.0
  - libpng=1.6.37
  - libstdcxx-ng=9.2.0
  - libtiff=4.1.0
  - markupsafe=1.1.1
  - mkl=2020.0
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - msgpack-python=0.6.1
  - ncurses=6.1
  - numpy=1.18.1
  - numpy-base=1.18.1
  - olefile=0.46
  - openssl=1.1.1d
  - packaging=20.1
  - pandas=1.0.1
  - parso=0.6.1
  - partd=1.1.0
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.0.0
  - pip=20.0.2
  - prompt_toolkit=3.0.3
  - psutil=5.6.7
  - ptyprocess=0.6.0
  - pygments=2.5.2
  - pyparsing=2.4.6
  - python=3.8.1
  - python-dateutil=2.8.1
  - pytz=2019.3
  - readline=8.0
  - setuptools=45.1.0
  - sqlite=3.30.1
  - tblib=1.6.0
  - tk=8.6.10
  - toolz=0.10.0
  - tornado=6.0.3
  - traitlets=4.3.3
  - wcwidth=0.1.8
  - wheel=0.34.2
  - xz=5.2.4
  - yaml=0.1.7
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - cbpro==1.1.4
    - cloudpickle==1.2.2
    - fastparquet==0.3.3
    - ipdb==0.12.3
    - llvmlite==0.31.0
    - locket==0.2.0
    - msgpack==0.6.2
    - multitasking==0.0.9
    - numba==0.48.0
    - pymongo==3.5.1
    - pystore==0.1.15
    - python-snappy==0.5.4
    - pyyaml==5.3
    - requests==2.13.0
    - six==1.10.0
    - sortedcontainers==2.1.0
    - ta==0.5.11
    - thrift==0.13.0
    - websocket-client==0.40.0
    - zict==1.0.0
prefix: /usr/local/anaconda3/envs/korova

