name: korova
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - backcall=0.1.0
  - blas=1.0
  - ca-certificates=2020.1.1
  - certifi=2019.11.28
  - decorator=4.4.1
  - intel-openmp=2020.0
  - ipython=7.12.0
  - ipython_genutils=0.2.0
  - jedi=0.16.0
  - ld_impl_linux-64=2.33.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcxx=9.0.1
  - libcxxabi=9.0.1
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgcc-ng=9.2.0
  - libgfortran=3.0.0
  - libgfortran-ng=7.3.0
  - libgomp=9.2.0
  - liblapack=3.8.0
  - libstdcxx-ng=9.2.0
  - mkl=2020.0
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - ncurses=6.1
  - numpy=1.18.1
  - numpy-base=1.18.1
  - openssl=1.1.1d
  - parso=0.6.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=20.0.2
  - prompt_toolkit=3.0.3
  - ptyprocess=0.6.0
  - pygments=2.5.2
  - python=3.8.1
  - readline=8.0
  - setuptools=45.1.0
  - sqlite=3.30.1
  - tk=8.6.10
  - traitlets=4.3.3
  - wcwidth=0.1.8
  - wheel=0.34.2
  - xz=5.2.4
  - zlib=1.2.11
  - pip:
    - cbpro==1.1.4
    - click==7.0
    - cloudpickle==1.2.2
    - dask==2.10.1
    - distributed==2.10.0
    - fastparquet==0.3.3
    - heapdict==1.0.1
    - llvmlite==0.31.0
    - locket==0.2.0
    - msgpack==0.6.2
    - multitasking==0.0.9
    - numba==0.48.0
    - pandas==1.0.1
    - partd==1.1.0
    - psutil==5.6.7
    - pymongo==3.5.1
    - pystore==0.1.15
    - python-dateutil==2.8.1
    - python-snappy==0.5.4
    - pytz==2019.3
    - pyyaml==5.3
    - requests==2.13.0
    - six==1.10.0
    - sortedcontainers==2.1.0
    - tblib==1.6.0
    - thrift==0.13.0
    - toolz==0.10.0
    - tornado==6.0.3
    - websocket-client==0.40.0
    - zict==1.0.0
prefix: /usr/local/anaconda3/envs/korova

